### ISSUE TITLE
Install matchbox package had non-zero exit status

### ISSUE THREAD

**Issue by Jolvii85** [mailund/matchbox#12]
Hi ,

I can't install the matchbox on my workstation,  can you help me to check the error?

Thank you.

Jolvii

---
>* installing *source* package ‘matchbox’ ...
>** R
>** byte-compile and prepare package for lazy loading
>Warning: `is_lang()` is deprecated as of rlang 0.2.0.
>Please use `is_call()` instead.
>This warning is displayed once per session.
>Warning: `list_len()` is deprecated as of rlang 0.2.0.
>Please use `new_list()` instead.
>This warning is displayed once per session.
>Warning: The function cannot be transformed since it contains a recursive call inside a call.
>Warning in tailr::loop_transform(llength) :
 > Could not build a transformed function
>Warning: The function cannot be transformed since it contains a recursive call inside a call.
>Warning in tailr::loop_transform(llrev) :
 > Could not build a transformed function
>Warning: The function cannot be transformed since it contains a recursive call inside a call.
>Warning in tailr::loop_transform(llcontains) :
 > Could not build a transformed function
>Warning: The function cannot be transformed since it contains a recursive call inside a call.
>Warning in tailr::loop_transform(lltake) :
 > Could not build a transformed function
>Warning: The function cannot be transformed since it contains a recursive call inside a call.
>Warning in tailr::loop_transform(llmap) :
>  Could not build a transformed function
>Error : 'transform_cases_function' is not an exported object from 'namespace:pmatch'
>Error : unable to load R code in package ‘matchbox’
>ERROR: lazy loading failed for package ‘matchbox’
>* removing ‘/pfs/nobackup/home/j/jolvii/Software/R_packages/matchbox’
>Error: Failed to install 'matchbox' from GitHub:
  >(converted from warning) installation of package >‘/tmp/RtmpeXdUCe/file9b7884d08d8a7/matchbox_0.0.0.9004.tar.gz’ had non-zero exit status

**Comment by obopodo** [comment]
Hi!
Got same issue. Did you manage how to fix that?

**Comment by mailund** [comment]
I think I managed to fix the problem but then I got an error on one of CRAN's test machine that I couldn't reproduce so I never uploaded the new function.

Right now, the GitHub version of the package is out of date and you cannot use it with the released versions of tailr and `pmatch`. I rewrote `pmatch` to make it more efficient and then I ran into two book deadlines and a lot of teaching so I never managed to update the package. I hope to get to it soon, and I probably should use some time on it now if you want to use it.

The changes to `pmatch` are that you cannot use `cases` any more but must define pattern-matching functions using either `case_func` or `case_trfunc` if you want the tail-recursive optimisation. I have a little time this morning so I will try to rewrite some of the functions but pull requests are very welcome.

I must warn you, though, that data structures based on pmatch are slow. They are mostly interesting from a programming point of view but the runtime matches can't compete with R's built-in functions. I was looking at compiling them into C code and match that way, but with two book deadline and contracts for two more, I don't know what the timeline for that is.

**Comment by mailund** [comment]
I updated all the simple data structures to use the new `pmatch` code. The continuation-passing-style implementation for the red-black search tree was a bit too complicated. I made a mistake so insertion isn't working any more, but I don't have the time to fix it now. I don't know when I will be able to get back to it.

In any case, because of the slow pattern matching I don't recommend that you use it before I have had a chance to solve that problem and that will be quite a bit into the future.

**Comment by obopodo** [comment]
Ok, thank you for the answer! I supposed to use GRoSS (paper says you took a part in developing), which depends on matchbox. So maybe I should ask Fernando Racimo if there is a way to get around using it.

**Comment by mailund** [comment]
It could be argued that it is probably my responsibility to fix GRoSS instead. Let me know what Fernando says

**Comment by obopodo** [comment]
I didn't mean that it's your responsibility)
Sure

**Comment by mailund** [comment]
I added that part to GRoSS so it would be my fault ;)

**Comment by obopodo** [comment]
Well Fernando said, that in current version of GRoSS there is no dependence on matchbox, I just downloaded an old one from link which was in the paper. So sorry for bothering

**Comment by mailund** [comment]
I saw his comment there. And no worries, it wasn't a bother.
